spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  jpa.show-sql: true
  jpa.properties:
    hibernate.format_sql: true

